install:
  - nuget restore

configuration:
  - Release

build:
  project: Its.Validation.sln
  publish_nuget: true

test:
  assemblies:
    - '**\*Tests.dll'

artifacts:
  - path: Validation\bin
    name: Its.Validation